version: "3.8"

services:
    worker:
        image: "{{ app_compose_image }}"
        devices:
            - "/dev/dri"
        environment:
            TZ: "America/Indiana/Indianapolis"
            PUID: "{{ app_user.uid }}"
            PGID: "{{ app_user.group }}"
            nodeName: "{{ app_tdarr_node_name }}"
            serverIP: "{{ app_tdarr_server_ip }}"
            serverPort: "8266"
        restart: "unless-stopped"
        volumes:
            - "./data/configs:/app/configs"
            - "./data/logs:/app/logs"
            - "./data/library:/library"
